-- ARMEND - seed Kitchen Stock (HARA): 119 item dari "Daily Kitchen Hara NEW.xlsx"
-- Harga & stok awal belum diisi (harga dari pricelist/import resep; stok awal dari opname).
-- Jalankan sekali di Supabase SQL Editor.

insert into public.outlets (id, name, parent_id, kind, area_type, order_idx)
select 'hara-kitchen', 'Kitchen Stock', o.id, 'area', 'kitchen', 2
from public.outlets o where o.name = 'HARA' and o.kind = 'group'
on conflict (id) do nothing;

insert into public.items (id, outlet_id, name, category, unit, item_type, stock, stock_tracking) values
  ('hara-kitchen-baby-romaine-250gr', 'hara-kitchen', 'Baby Romaine @250gr', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-bawang-bombay', 'hara-kitchen', 'Bawang Bombay', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-daun-basil', 'hara-kitchen', 'Daun Basil', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-jamur-champignon-5kg-dus', 'hara-kitchen', 'Jamur Champignon (5kg/dus)', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-lettuce-ice-berg', 'hara-kitchen', 'Lettuce Ice Berg', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-salanova-green-butterhead-250grm', 'hara-kitchen', 'Salanova Green Butterhead @250grm', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-salanova-red-butterhead-250grm', 'hara-kitchen', 'Salanova Red Butterhead @250grm', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-selada-hijau-250grm-kitchen-hara', 'hara-kitchen', 'Selada Hijau @250grm (Kitchen Hara)', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-tomat-cherry', 'hara-kitchen', 'Tomat Cherry', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-tomat-merah', 'hara-kitchen', 'Tomat Merah', 'SAYURAN', 'kg', 'RAW', 0, true),
  ('hara-kitchen-anchor-processed-cheese-easy-cheddar-cheese-2-kg', 'hara-kitchen', 'Anchor Processed Cheese Easy (Cheddar Cheese) 2 kg', 'KEJU & DAIRY', 'kg', 'RAW', 0, true),
  ('hara-kitchen-blue-band-whipping-cooking-cream-1l', 'hara-kitchen', 'Blue Band Whipping Cooking Cream @1L', 'KEJU & DAIRY', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-butter-bulk-unsalted-25-kg', 'hara-kitchen', 'Butter Bulk Unsalted @ 25 kg', 'KEJU & DAIRY', 'kg', 'RAW', 0, true),
  ('hara-kitchen-diamond-susu-uht-1l', 'hara-kitchen', 'Diamond Susu Uht @ 1L', 'KEJU & DAIRY', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-green-valey-keju-parmesan-1-kg', 'hara-kitchen', 'Green Valey - Keju Parmesan @1 kg', 'KEJU & DAIRY', 'kg', 'RAW', 0, true),
  ('hara-kitchen-keju-cheddar-orange-red-mimolet', 'hara-kitchen', 'Keju Cheddar Orange (Red)/Mimolet', 'KEJU & DAIRY', 'kg', 'RAW', 0, true),
  ('hara-kitchen-keju-mozarella-urial-2-5-kg', 'hara-kitchen', 'Keju Mozarella Urial @2,5 kg', 'KEJU & DAIRY', 'kg', 'RAW', 0, true),
  ('hara-kitchen-beras-gemar-jasmin', 'hara-kitchen', 'Beras Gemar Jasmin', 'BERAS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-beras-jepang-mekar-wangi', 'hara-kitchen', 'Beras Jepang (mekar wangi)', 'BERAS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-la-fonte-linguine-500-gr-pack-20-ctn', 'hara-kitchen', 'La Fonte Linguine @ 500 gr / pack (20/ctn)', 'PASTA', 'portion', 'RAW', 0, true),
  ('hara-kitchen-la-fonte-penne-500gr', 'hara-kitchen', 'La Fonte Penne @500gr', 'PASTA', 'portion', 'RAW', 0, true),
  ('hara-kitchen-la-fonte-spaghetti-11-1-kg-pack-10-ctn', 'hara-kitchen', 'La Fonte Spaghetti - 11 @1 kg / pack (10/ctn)', 'PASTA', 'portion', 'RAW', 0, true),
  ('hara-kitchen-san-remo-rigatoni-500grm', 'hara-kitchen', 'San Remo Rigatoni @500grm', 'PASTA', 'portion', 'RAW', 0, true),
  ('hara-kitchen-bertolli-extra-virgin-olive-1-lt-6-ctn', 'hara-kitchen', 'Bertolli Extra virgin olive 1 lt/6/ctn', 'MINYAK', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-lily-salad-oil-3-ltr-6-ctn', 'hara-kitchen', 'Lily Salad Oil 3 ltr / 6 / ctn', 'MINYAK', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-minyak-goreng-sedap-20-lt-jrg', 'hara-kitchen', 'Minyak goreng Sedap 20 lt / jrg', 'MINYAK', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-delmonte-tomato-galon-5-7-kg', 'hara-kitchen', 'Delmonte Tomato Galon @ 5,7 kg', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-kecap-manis-bango-6-5-kg-3-lt', 'hara-kitchen', 'Kecap manis Bango @6,5 kg / 3 lt', 'SAUCE & BUMBU', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-kewpie-mayonaise-base-3kg-4-ctn', 'hara-kitchen', 'Kewpie Mayonaise Base 3kg/ 4 /ctn', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-knorr-ayam-bumbu-1-kg-6-ctn', 'hara-kitchen', 'Knorr Ayam bumbu @ 1 kg/6/ctn', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-knorr-demi-glace-1-kg-6-ctn', 'hara-kitchen', 'Knorr Demi Glace @ 1 kg/6/ctn', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-knorr-mashed-potato-4kg', 'hara-kitchen', 'Knorr Mashed Potato @4kg', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-knorr-sapi-bumbu-1-kg-6-pile-ctn', 'hara-kitchen', 'Knorr Sapi bumbu @ 1 kg/6 pile/ctn', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-knorr-tom-yam-pst-1-5-kg-pile', 'hara-kitchen', 'Knorr Tom Yam Pst @ 1,5 kg / pile', 'SAUCE & BUMBU', 'kg', 'RAW', 0, true),
  ('hara-kitchen-mama-lime-1-5l', 'hara-kitchen', 'Mama Lime 1,5L', 'SAUCE & BUMBU', 'pouch', 'RAW', 0, true),
  ('hara-kitchen-sauce-bbq-1kg-pack', 'hara-kitchen', 'Sauce BBQ (1kg/pack)', 'SAUCE & BUMBU', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-sauce-hokkaido-bbq-kg', 'hara-kitchen', 'Sauce Hokkaido BBQ/KG', 'SAUCE & BUMBU', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-sauce-teriyaki-1kg-pack', 'hara-kitchen', 'Sauce Teriyaki (1kg/pack)', 'SAUCE & BUMBU', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-sauce-yakiniku-kg', 'hara-kitchen', 'Sauce Yakiniku/kg', 'SAUCE & BUMBU', 'ltr', 'RAW', 0, true),
  ('hara-kitchen-almond-slice-1-kg', 'hara-kitchen', 'Almond Slice @ 1 kg', 'DRY GOODS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-bawang-goreng-sumenep-500gr', 'hara-kitchen', 'Bawang Goreng Sumenep @500gr', 'DRY GOODS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-golden-farm-kernel-corn-1kg-pack', 'hara-kitchen', 'Golden Farm Kernel Corn @1kg/pack', 'DRY GOODS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-kanayakan-bawang-putih-goreng-500-gr-pack', 'hara-kitchen', 'Kanayakan Bawang Putih goreng @ 500 gr/pack', 'DRY GOODS', 'kg', 'RAW', 0, true),
  ('hara-kitchen-beef-bacon-20gr', 'hara-kitchen', 'Beef Bacon @20gr', 'BEEF', 'slice', 'RAW', 0, true),
  ('hara-kitchen-stock-beef-patty-100gr', 'hara-kitchen', 'Stock Beef Patty @100gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-beef-saikoro-130-gr', 'hara-kitchen', 'Stock Beef Saikoro @130 gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-gyuniku-120gr-3-slice', 'hara-kitchen', 'Stock Gyuniku @120gr ( 3 Slice)', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-iga-soup-160gr-matang', 'hara-kitchen', 'Stock Iga Soup @160gr (matang)', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-oxtail-soup-140gr', 'hara-kitchen', 'Stock Oxtail Soup @140gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-sirloin-steak-180gr', 'hara-kitchen', 'Stock Sirloin Steak 180gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-soto-betawi-80gr', 'hara-kitchen', 'Stock Soto Betawi @80gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-tenderloin-200gr', 'hara-kitchen', 'Stock Tenderloin 200gr', 'BEEF', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-tenderloin-80gr', 'hara-kitchen', 'Stock Tenderloin @80gr', 'BEEF', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-bandeng-cabut-duri-300-350gr', 'hara-kitchen', 'Bandeng Cabut Duri @300-350gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-dori-mentai-80gr', 'hara-kitchen', 'Dori Mentai @80gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-salmon-aglio-50-gr', 'hara-kitchen', 'Salmon Aglio @50 gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-salmon-pesto-100-gr', 'hara-kitchen', 'Salmon Pesto @100 gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-salmon-teryaki-80-gr', 'hara-kitchen', 'Salmon Teryaki @80 gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-grill-salmon-head', 'hara-kitchen', 'Stock Grill Salmon Head', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-salmon-35-gr', 'hara-kitchen', 'Stock Salmon @35 gr', 'FISH & SEAFOOD', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-udang-windu-prawn-tomyum-2-pcs', 'hara-kitchen', 'Stock Udang Windu PRAWN TOMYUM @2 pcs', 'FISH & SEAFOOD', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-ayam-taliwang', 'hara-kitchen', 'Ayam Taliwang', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-fillet-dada-utuh-100gr', 'hara-kitchen', 'Fillet Dada Utuh 100gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-fillet-dada-utuh-150gr', 'hara-kitchen', 'Fillet Dada Utuh 150gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-ayam-pejantan-ekor-4-porsi', 'hara-kitchen', 'Stock Ayam Pejantan /ekor (4 Porsi)', 'POULTRY', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-stock-chicken-katsu-100-gr', 'hara-kitchen', 'Stock Chicken Katsu @100 gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-chicken-wings-100gr', 'hara-kitchen', 'Stock Chicken Wings @100gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-chicken-wings-50gr-mix-platter', 'hara-kitchen', 'Stock Chicken Wings @50gr Mix Platter', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-dada-sous-vide-100gr', 'hara-kitchen', 'Stock Dada Sous vide 100gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-paha-100gr', 'hara-kitchen', 'Stock Paha 100gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-paha-fillet-utuh-150gr', 'hara-kitchen', 'Stock Paha Fillet Utuh 150gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-paha-parmagiana-100gr', 'hara-kitchen', 'Stock Paha Parmagiana @100gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-paha-pentung-100-gr', 'hara-kitchen', 'Stock Paha Pentung @100 gr', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-satay-ayam', 'hara-kitchen', 'Stock Satay Ayam', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-satay-ayam-fried-rice-green-chilli-2pcs-port', 'hara-kitchen', 'Stock Satay Ayam Fried Rice (Green Chilli @2pcs/port)', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-stock-satay-kambing-per-portion-8pcs-port', 'hara-kitchen', 'Stock Satay Kambing Per Portion (8pcs/port)', 'POULTRY', 'portion', 'RAW', 0, true),
  ('hara-kitchen-bumbu-satay', 'hara-kitchen', 'Bumbu Satay', 'OTHERS', 'portion', 'RAW', 0, true),
  ('hara-kitchen-corn-tortillas-60-slice-pack', 'hara-kitchen', 'Corn Tortillas @60 slice/pack', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-croquette-holland', 'hara-kitchen', 'Croquette Holland', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-gb-roti-burger', 'hara-kitchen', 'GB - Roti Burger', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-gb-cheese-slice-reguler-orange-84-slice', 'hara-kitchen', 'GB Cheese Slice Reguler (Orange) / 84 slice', 'OTHERS', 'slice', 'RAW', 0, true),
  ('hara-kitchen-komugi-gandum', 'hara-kitchen', 'Komugi Gandum', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-komugi-tawar-putih', 'hara-kitchen', 'Komugi Tawar Putih', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-mccain-original-choice-shoestring-100gr', 'hara-kitchen', 'McCain Original Choice Shoestring @100gr', 'OTHERS', 'gr', 'RAW', 0, true),
  ('hara-kitchen-mccain-original-choice-shoestring-120gr', 'hara-kitchen', 'McCain Original Choice Shoestring @120gr', 'OTHERS', 'gr', 'RAW', 0, true),
  ('hara-kitchen-mccain-straight-cut-1-kg-10pack-ctn-150gr', 'hara-kitchen', 'McCain Straight Cut @ 1 kg (10pack/ctn) @150gr', 'OTHERS', 'gr', 'RAW', 0, true),
  ('hara-kitchen-mie', 'hara-kitchen', 'Mie', 'OTHERS', 'portion', 'RAW', 0, true),
  ('hara-kitchen-spinach-cake', 'hara-kitchen', 'Spinach Cake', 'OTHERS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-dilamo-smoked-beef-b-1kg-40-slice', 'hara-kitchen', 'Dilamo Smoked Beef (B) @ 1kg/40 slice', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-garlic-bread', 'hara-kitchen', 'GARLIC BREAD', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-hash-brown', 'hara-kitchen', 'Hash Brown', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-meister-beef-cocktail-breakfast-36pcs-kg', 'hara-kitchen', 'Meister - Beef Cocktail Breakfast @36pcs/kg', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-roti-gandum-1-loaf-9-portion', 'hara-kitchen', 'Roti Gandum (1 loaf = 9 portion)', 'BRUNCH', 'portion', 'RAW', 0, true),
  ('hara-kitchen-sourdogh-1-5cm', 'hara-kitchen', 'Sourdogh 1,5cm', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-sourdogh-2-cm', 'hara-kitchen', 'Sourdogh 2 cm', 'BRUNCH', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-banana-fritter', 'hara-kitchen', 'Banana Fritter', 'LIGHT MEALS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-cakwe-10-pcs', 'hara-kitchen', 'Cakwe @10/PCS', 'LIGHT MEALS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-cassava-thai-sauce', 'hara-kitchen', 'Cassava Thai Sauce', 'LIGHT MEALS', 'portion', 'RAW', 0, true),
  ('hara-kitchen-coklat-lava', 'hara-kitchen', 'Coklat Lava', 'LIGHT MEALS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-matcha-lava', 'hara-kitchen', 'Matcha Lava', 'LIGHT MEALS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-roti-kasino', 'hara-kitchen', 'Roti Kasino', 'LIGHT MEALS', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-dilamo-sosis-beef-cocktail-1000-sb-48-pack', 'hara-kitchen', 'Dilamo Sosis Beef Cocktail 1000 SB /48 / pack', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-fillet-dada-ayam', 'hara-kitchen', 'Fillet Dada Ayam', 'BREAKFAST', 'kg', 'RAW', 0, true),
  ('hara-kitchen-indomie-goreng', 'hara-kitchen', 'Indomie Goreng', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-indomie-rebus', 'hara-kitchen', 'Indomie Rebus', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-melon', 'hara-kitchen', 'Melon', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-pepaya', 'hara-kitchen', 'Pepaya', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-pineapple-jam', 'hara-kitchen', 'Pineapple Jam', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-roti-croissant-kotak', 'hara-kitchen', 'Roti Croissant Kotak', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-roti-gandum', 'hara-kitchen', 'Roti Gandum', 'BREAKFAST', 'loaf', 'RAW', 0, true),
  ('hara-kitchen-roti-tawar', 'hara-kitchen', 'Roti Tawar', 'BREAKFAST', 'loaf', 'RAW', 0, true),
  ('hara-kitchen-sedap-goreng', 'hara-kitchen', 'Sedap Goreng', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-sedap-rebus', 'hara-kitchen', 'Sedap Rebus', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-semangka', 'hara-kitchen', 'Semangka', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-siomay', 'hara-kitchen', 'Siomay', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-snowvalley-straight-cut', 'hara-kitchen', 'Snowvalley Straight Cut', 'BREAKFAST', 'gr', 'RAW', 0, true),
  ('hara-kitchen-strawberry-jam', 'hara-kitchen', 'Strawberry Jam', 'BREAKFAST', 'pcs', 'RAW', 0, true),
  ('hara-kitchen-telur-ayam-negeri', 'hara-kitchen', 'Telur Ayam Negeri', 'BREAKFAST', 'kg', 'RAW', 0, true),
  ('hara-kitchen-trimming-tenderloin', 'hara-kitchen', 'Trimming Tenderloin', 'BREAKFAST', 'kg', 'RAW', 0, true)
on conflict (id) do nothing;
