-- HARA Bar Control — seed data (from the original spreadsheet)
-- Run this once after schema.sql, on the same Supabase project.

insert into public.items (id, name, category, unit, item_type, stock_tracking, stock, needs_order, order_idx) values
('hara-blend-1kg', 'Hara Blend @1kg', 'BEVERAGE', 'gr', 'RAW', true, 1590, false, 0),
('oh-java-cocoa-powder-dark-1kg', 'Oh Java Cocoa Powder Dark @1kg', 'BEVERAGE', 'gr', 'RAW', true, 449, false, 1),
('matcha-flavor-powder-500grm', 'Matcha Flavor Powder @500grm', 'BEVERAGE', 'gr', 'RAW', true, 0, false, 2),
('squeeze-guava-buffet-5lt', 'Squeeze Guava Buffet 5lt', 'BEVERAGE', 'ml', 'RAW', false, 0, false, 3),
('squeeze-lemon-juice-1l', 'Squeeze Lemon Juice 1L', 'BEVERAGE', 'ml', 'RAW', false, 0, false, 4),
('sun-fresh-orange-juice-2lt', 'Sun Fresh Orange Juice 2lt', 'BEVERAGE', 'ml', 'RAW', true, 1750, false, 5),
('toza-orange-juice-5lt-breakfast', 'Toza Orange Juice 5lt (Breakfast)', 'BEVERAGE', 'ml', 'RAW', false, 5000, false, 6),
('sprite', 'Sprite', 'BEVERAGE', 'can', 'RAW', false, 5, false, 7),
('fanta-soda-water-12botol-krat', 'Fanta Soda Water @12botol/krat', 'BEVERAGE', 'botol', 'RAW', false, 5, false, 8),
('happy-day-jus-pineapple-1ltr', 'Happy Day Jus Pineapple 1ltr', 'BEVERAGE', 'ml', 'RAW', true, 0, false, 9),
('hydro-coco-250-ml', 'Hydro Coco 250 ml', 'BEVERAGE', 'pcs', 'RAW', true, 2, false, 10),
('pisang', 'Pisang', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 1300, false, 11),
('buah-naga', 'Buah Naga', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 750, false, 12),
('jeruk-sunkist-kg', 'Jeruk Sunkist / kg', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 3600, false, 13),
('lemon-lokal-kg', 'Lemon Lokal / kg', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', false, 0, false, 14),
('semangka-merah', 'Semangka Merah', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 1700, false, 15),
('kyuri', 'Kyuri', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 0, false, 16),
('nanas', 'Nanas', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 900, false, 17),
('caisim', 'Caisim', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 350, false, 18),
('strawberry-frozen', 'Strawberry Frozen', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 1450, false, 19),
('strawberry-garnish', 'Strawberry Garnish', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', false, 100, false, 20),
('daun-mint', 'Daun Mint', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', false, 0, false, 21),
('rosemary', 'Rosemary', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', false, 50, false, 22),
('biji-pala', 'Biji Pala', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', false, 30, false, 23),
('jeruk-medan', 'Jeruk Medan', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 1350, false, 24),
('tomat-merah', 'Tomat Merah', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 585, false, 25),
('wortel', 'Wortel', 'BUAH-BUAHAN & SAYURAN', 'gr', 'RAW', true, 500, false, 26),
('palm-sugar-1-kg-pack', 'Palm Sugar 1 kg / pack', 'GROCERIES', 'gr', 'RAW', true, 650, false, 27),
('brown-sugar-stick-250-pcs-pack', 'Brown Sugar Stick 250 pcs/ pack', 'GROCERIES', 'pcs', 'RAW', true, 60, false, 28),
('white-sugar-stick-250-pcs-pack', 'White Sugar Stick 250 pcs /pack', 'GROCERIES', 'pcs', 'RAW', true, 200, false, 29),
('tropicana-slim-sachet-100-pcs', 'Tropicana Slim Sachet @ 100 pcs', 'GROCERIES', 'pcs', 'RAW', true, 170, false, 30),
('madu-nusantara', 'Madu Nusantara', 'GROCERIES', 'ml', 'RAW', true, 340, false, 31),
('gula-pasir-1kg-pack', 'Gula Pasir 1kg/pack', 'GROCERIES', 'pack', 'RAW', false, 2, false, 32),
('mamata-leci', 'Mamata Leci', 'GROCERIES', 'can', 'RAW', false, 1, false, 33),
('millac-gold-cream-whipping-1-lt', 'Millac Gold Cream Whipping 1 lt', 'GROCERIES', 'ml', 'RAW', true, 1000, false, 34),
('pistachio-powder', 'Pistachio Powder', 'GROCERIES', 'gr', 'RAW', true, 270, false, 35),
('wilmond-peach-halves', 'Wilmond Peach Halves', 'GROCERIES', 'gr', 'RAW', true, 170, false, 36),
('dried-lemon-slice', 'Dried Lemon Slice', 'GROCERIES', 'slice', 'RAW', true, 5, false, 37),
('kacang-mede', 'Kacang Mede', 'GROCERIES', 'kg', 'RAW', true, 202, false, 38),
('la-kreiva-crumble-caramel-250grm', 'La Kreiva Crumble CarameL @250grm', 'GROCERIES', 'gr', 'RAW', true, 0, false, 39),
('the-purest-sea-salt-fine-300grm', 'The Purest Sea Salt Fine @300grm', 'GROCERIES', 'gr', 'RAW', false, 159, false, 40),
('biji-selasih-50-gr-pack', 'Biji Selasih 50 gr/ pack', 'GROCERIES', 'gr', 'RAW', false, 50, false, 41),
('dried-pineapple', 'Dried Pineapple', 'GROCERIES', 'pcs', 'RAW', false, 11, false, 42),
('greenfields-fresh-milk-1-lt-12-pack-ctn', 'Greenfields Fresh Milk 1 lt /@12 pack / ctn', 'DAIRY PRODUCT', 'ml', 'RAW', true, 7960, false, 43),
('skm-carnation-370-gr', 'SKM Carnation 370 gr', 'DAIRY PRODUCT', 'can', 'RAW', true, 2, false, 44),
('ice-cream-diamond-vanilla-8-lt', 'Ice Cream Diamond - Vanilla 8 lt', 'DAIRY PRODUCT', 'gr', 'RAW', true, 6800, false, 45),
('greenfields-yogurt-plain-125gr-pack', 'Greenfields Yogurt plain 125gr/pack', 'DAIRY PRODUCT', 'gr', 'RAW', true, 280, false, 46),
('oatside-oatmilk-barista-blend-1l', 'Oatside Oatmilk Barista Blend @1L', 'DAIRY PRODUCT', 'ml', 'RAW', true, 500, false, 47),
('giffard-hazelnut-syrup-1lt', 'Giffard Hazelnut Syrup 1Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 400, false, 48),
('giffard-caramel-syrup-1lt', 'Giffard Caramel Syrup 1Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 905, false, 49),
('giffard-syrup-peach-1lt', 'Giffard Syrup Peach @1Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 550, false, 50),
('monin-geradine-700-ml', 'Monin Geradine 700 ml', 'SYRUP PRODUCT', 'ml', 'RAW', true, 650, false, 51),
('monin-lychee-1lt', 'Monin Lychee 1Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 20, false, 52),
('monin-mojito-wild-mint-1-lt', 'Monin Mojito /Wild Mint 1 Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 560, false, 53),
('monin-strawberry-puree-1-lt', 'Monin Strawberry puree 1 Lt', 'SYRUP PRODUCT', 'ml', 'RAW', true, 920, false, 54),
('dripp-orange-760-ml', 'Dripp Orange 760 Ml', 'SYRUP PRODUCT', 'ml', 'RAW', true, 360, false, 55),
('dripp-passion-fruit-760-ml', 'Dripp Passion Fruit 760 Ml', 'SYRUP PRODUCT', 'ml', 'RAW', true, 750, false, 56),
('dripp-osmantus-760-ml', 'Dripp Osmantus 760 Ml', 'SYRUP PRODUCT', 'ml', 'RAW', true, 420, false, 57),
('yuzu-marmalade-kaeru-yuzu-500-gr', 'Yuzu Marmalade (Kaeru Yuzu) 500 gr', 'SYRUP PRODUCT', 'gr', 'RAW', true, 320, false, 58),
('stir-up-pistachio-800-ml', 'Stir Up Pistachio 800 Ml', 'SYRUP PRODUCT', 'ml', 'RAW', true, 1030, false, 59),
('goalpara-black-tea-250-gr-pack', 'Goalpara Black Tea 250 gr/ pack', 'TEA PRODUCT', 'gr', 'RAW', false, 90, false, 60),
('havilla-queensberry-voyage-55-tea-bag-pack', 'Havilla Queensberry Voyage 55 tea bag/ pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 37, false, 61),
('havilla-new-year-fest-55-tea-bag-pack', 'Havilla New Year Fest 55 tea bag/ pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 48, false, 62),
('havilla-chamomile-55-tea-bag-pack', 'Havilla Chamomile 55 tea bag/ pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 54, false, 63),
('havilla-blue-harmony-55-tea-bag-pack', 'Havilla Blue Harmony 55 tea bag/ pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 38, false, 64),
('twinnings-earl-grey-25-tea-bag-pack', 'Twinnings Earl Grey 25 tea bag/pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 8, false, 65),
('twinnings-english-breakfast-25-tea-bag-pack', 'Twinnings English Breakfast 25 tea bag/pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 0, false, 66),
('twinnings-green-tea-jasmine-25-tea-bag-pack', 'Twinnings Green Tea Jasmine 25 tea bag/pack', 'TEA PRODUCT', 'pcs', 'RAW', true, 14, false, 67),
('cup-hot-papercup-doublewall-8oz-craft-black-lid', 'Cup Hot Papercup Doublewall 8oz Craft + black lid', 'PACKAGING', 'pcs', 'RAW', false, 90, false, 68),
('cup-pp-injection-12oz-clear-lid', 'Cup PP Injection 12oz clear + lid', 'PACKAGING', 'pcs', 'RAW', false, 100, false, 69),
('stirrer-papercup', 'Stirrer Papercup', 'PACKAGING', 'pack', 'RAW', false, 4, false, 70),
('cassava-straw-6mm-x-20cm-100pcs', 'Cassava Straw 6mm x 20cm @100pcs', 'PACKAGING', 'pcs', 'RAW', false, 1200, false, 71),
('cassava-straw-8mm-x-20cm-100pcs', 'Cassava Straw 8mm x 20cm @100pcs', 'PACKAGING', 'pcs', 'RAW', false, 400, false, 72),
('plastik-buram-hdtp-tipis-10x20-kg-kiloan', 'Plastik Buram HDTP Tipis 10x20 /kg ( kiloan )', 'PACKAGING', 'kg', 'RAW', false, 0.6, false, 73),
('plastik-wrap-30cm', 'Plastik Wrap 30cm', 'PACKAGING', 'roll', 'RAW', false, 1, false, 74),
('trashbag-80x120-lotus', 'Trashbag 80x120 (Lotus)', 'PACKAGING', 'pack', 'RAW', false, 2, false, 75),
('thermal-papper-80-x-80-bill', 'Thermal Papper 80 x 80 (Bill)', 'PACKAGING', 'roll', 'RAW', false, 5, false, 76),
('bamboo-stick-skeweer-12-100-pack', 'Bamboo Stick Skeweer 12''/100/pack', 'PACKAGING', 'pcs', 'RAW', false, 3, false, 77),
('plenty-cocktail-napkin-48-ctn', 'Plenty Cocktail Napkin / 48/ctn', 'PACKAGING', 'pack', 'RAW', false, 7, false, 78),
('plastik-t-untuk-take-away', 'Plastik T untuk take away', 'PACKAGING', 'pack', 'RAW', false, 1, false, 79),
('amidis-galon', 'AMIDIS GALON', 'OTHERS', 'galon', 'RAW', false, 2, false, 80),
('aqua-galon', 'AQUA GALON', 'OTHERS', 'galon', 'RAW', false, 2, false, 81),
('mama-lime-pouch-1-5l', 'Mama Lime Pouch 1,5L', 'OTHERS', 'ltr', 'RAW', false, 2100, false, 82),
('susemi-sabut-kawat-40gr', 'Susemi Sabut Kawat 40gr', 'OTHERS', 'pcs', 'RAW', false, 0, false, 83),
('polytex-sabut-spoon-regular-kuning-hijau', 'Polytex Sabut spoon Regular/ Kuning Hijau', 'OTHERS', 'pcs', 'RAW', false, 4, false, 84),
('snap-clean-liquid-detergent-5lt', 'Snap Clean Liquid Detergent 5lt', 'OTHERS', 'ltr', 'RAW', false, 6000, false, 85),
('gas-portable-purity', 'Gas portable purity', 'OTHERS', 'can', 'RAW', false, 2, false, 86),
('coffe-clean-detergent-900gr', 'Coffe Clean Detergent @900gr', 'OTHERS', 'grm', 'RAW', false, 1230, false, 87),
('kopi-gula-aren', 'Kopi Gula Aren', 'PREP', 'ml', 'PREP', false, 0, false, 88),
('cold-brew-base', 'Cold Brew Base', 'PREP', 'ml', 'PREP', false, 0, false, 89),
('base-cream', 'Base Cream', 'PREP', 'ml', 'PREP', false, 0, false, 90),
('tea-based', 'Tea Based', 'PREP', 'ml', 'PREP', false, 0, false, 91);

insert into public.menu (id, name, category, active, order_idx) values
('english-breakfast', 'English breakfast', 'Tea', true, 0),
('green-tea-jasmine', 'Green tea jasmine', 'Tea', true, 1),
('earl-grey', 'Earl grey', 'Tea', true, 2),
('ice-regular-tea', 'Ice regular tea', 'Tea', true, 3),
('ice-lychee-tea', 'Ice lychee tea', 'Tea', true, 4),
('ice-lemon-tea', 'Ice lemon tea', 'Tea', true, 5),
('hot-lemon-tea', 'Hot lemon tea', 'Tea', true, 6),
('new-year-fest', 'New year fest', 'Artisan Tea', true, 7),
('queen-s-choice', 'Queen''s Choice', 'Artisan Tea', true, 8),
('chamomile', 'Chamomile', 'Artisan Tea', true, 9),
('blue-harmony', 'Blue Harmony', 'Artisan Tea', true, 10),
('passion-fruit-tea', 'Passion fruit tea', 'Tea', true, 11),
('berry-iced-tea', 'Berry iced tea', 'Tea', true, 12),
('strawberry-juices', 'Strawberry juices', 'Juices', true, 13),
('orange-juices', 'Orange juices', 'Juices', true, 14),
('watermelon-juice', 'Watermelon Juice', 'Juices', true, 15),
('greenrush-juice', 'Greenrush juice', 'Juices', true, 16),
('citrus-blast-juice', 'Citrus blast juice', 'Juices', true, 17),
('pineapple-juice', 'Pineapple juice', 'Juices', true, 18),
('detox-juice', 'Detox juice', 'Juices', true, 19),
('red-smoothies', 'Red smoothies', 'Juices', true, 20),
('orange-smothies', 'Orange smothies', 'Juices', true, 21),
('virgin-mojito', 'Virgin mojito', 'Mocktails', true, 22),
('lyhchee-mojito', 'Lyhchee mojito', 'Mocktails', true, 23),
('strawberry-mojito', 'Strawberry mojito', 'Mocktails', true, 24),
('yellow-submarine', 'Yellow submarine', 'Mocktails', true, 25),
('cappucino-hot', 'Cappucino hot', 'Classic Coffee', true, 26),
('latte-hot', 'Latte hot', 'Classic Coffee', true, 27),
('latte-ice', 'Latte Ice', 'Classic Coffee', true, 28),
('magic-hot', 'Magic hot', 'Classic Coffee', true, 29),
('creme-brulee', 'Creme brulee', 'Classic Coffee', true, 30),
('black-coffee-hot', 'Black coffee hot', 'Classic Coffee', true, 31),
('black-coffee-ice', 'Black coffee ice', 'Classic Coffee', true, 32),
('affogato', 'Affogato', 'Classic Coffee', true, 33),
('hara-iced-coffee', 'Hara iced coffee', 'Signature Coffee', true, 34),
('pistachio-cloud-latte', 'Pistachio cloud latte', 'Signature Coffee', true, 35),
('sea-salt-cloud-latte', 'Sea salt cloud latte', 'Signature Coffee', true, 36),
('salted-caramel-cloud-latte', 'Salted caramel cloud latte', 'Signature Coffee', true, 37),
('spanish-latte-hot', 'Spanish latte hot', 'Signature Coffee', true, 38),
('spanish-latte-ice', 'Spanish latte ice', 'Signature Coffee', true, 39),
('hazelnut-caramel-latte', 'Hazelnut caramel latte', 'Signature Coffee', true, 40),
('yuzu-black', 'Yuzu black', 'Signature Coffee', true, 41),
('peach-black', 'Peach black', 'Signature Coffee', true, 42),
('punchpresso', 'Punchpresso', 'Signature Coffee', true, 43),
('cold-brew', 'Cold brew', 'Cold Brew', true, 44),
('mont-blanc', 'Mont blanc', 'Cold Brew', true, 45),
('dark-berry', 'Dark berry', 'Cold Brew', true, 46),
('matcha-latte-hot', 'Matcha latte hot', 'Non-Coffee', true, 47),
('matcha-latte-iced', 'Matcha latte iced', 'Non-Coffee', true, 48),
('chocolatte-hot', 'Chocolatte hot', 'Non-Coffee', true, 49),
('chocolatte-iced', 'Chocolatte iced', 'Non-Coffee', true, 50);

insert into public.recipe_ingredients (menu_id, item_id, qty, unit) values
('english-breakfast', 'twinnings-english-breakfast-25-tea-bag-pack', 1, 'pcs'),
('green-tea-jasmine', 'twinnings-green-tea-jasmine-25-tea-bag-pack', 1, 'pcs'),
('earl-grey', 'twinnings-earl-grey-25-tea-bag-pack', 1, 'pcs'),
('ice-regular-tea', 'tea-based', 250, 'ml'),
('ice-lychee-tea', 'tea-based', 250, 'ml'),
('ice-lychee-tea', 'monin-lychee-1lt', 30, 'ml'),
('ice-lemon-tea', 'tea-based', 250, 'ml'),
('hot-lemon-tea', 'twinnings-english-breakfast-25-tea-bag-pack', 1, 'pcs'),
('hot-lemon-tea', 'white-sugar-stick-250-pcs-pack', 1, 'pcs'),
('new-year-fest', 'havilla-new-year-fest-55-tea-bag-pack', 1, 'pcs'),
('queen-s-choice', 'havilla-queensberry-voyage-55-tea-bag-pack', 1, 'pcs'),
('chamomile', 'havilla-chamomile-55-tea-bag-pack', 1, 'pcs'),
('blue-harmony', 'havilla-blue-harmony-55-tea-bag-pack', 1, 'pcs'),
('passion-fruit-tea', 'dripp-passion-fruit-760-ml', 30, 'ml'),
('passion-fruit-tea', 'tea-based', 250, 'ml'),
('berry-iced-tea', 'monin-strawberry-puree-1-lt', 30, 'ml'),
('berry-iced-tea', 'dripp-osmantus-760-ml', 10, 'ml'),
('berry-iced-tea', 'tea-based', 250, 'ml'),
('strawberry-juices', 'strawberry-frozen', 150, 'gr'),
('strawberry-juices', 'monin-strawberry-puree-1-lt', 20, 'ml'),
('orange-juices', 'jeruk-sunkist-kg', 350, 'gr'),
('orange-juices', 'sun-fresh-orange-juice-2lt', 100, 'ml'),
('orange-juices', 'jeruk-sunkist-kg', 20, 'gr'),
('watermelon-juice', 'semangka-merah', 450, 'gr'),
('greenrush-juice', 'nanas', 50, 'gr'),
('greenrush-juice', 'caisim', 50, 'gr'),
('greenrush-juice', 'happy-day-jus-pineapple-1ltr', 100, 'ml'),
('citrus-blast-juice', 'jeruk-medan', 100, 'gr'),
('citrus-blast-juice', 'wortel', 100, 'gr'),
('citrus-blast-juice', 'tomat-merah', 100, 'gr'),
('citrus-blast-juice', 'sun-fresh-orange-juice-2lt', 100, 'ml'),
('pineapple-juice', 'nanas', 100, 'gr'),
('pineapple-juice', 'happy-day-jus-pineapple-1ltr', 100, 'ml'),
('detox-juice', 'nanas', 50, 'gr'),
('detox-juice', 'kyuri', 80, 'gr'),
('detox-juice', 'happy-day-jus-pineapple-1ltr', 100, 'ml'),
('red-smoothies', 'pisang', 100, 'gr'),
('red-smoothies', 'buah-naga', 50, 'gr'),
('red-smoothies', 'greenfields-yogurt-plain-125gr-pack', 40, 'gr'),
('red-smoothies', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 100, 'ml'),
('orange-smothies', 'jeruk-sunkist-kg', 100, 'gr'),
('orange-smothies', 'dripp-orange-760-ml', 20, 'ml'),
('orange-smothies', 'greenfields-yogurt-plain-125gr-pack', 40, 'gr'),
('orange-smothies', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 100, 'ml'),
('virgin-mojito', 'monin-mojito-wild-mint-1-lt', 20, 'ml'),
('lyhchee-mojito', 'monin-lychee-1lt', 20, 'ml'),
('lyhchee-mojito', 'monin-mojito-wild-mint-1-lt', 20, 'ml'),
('strawberry-mojito', 'monin-strawberry-puree-1-lt', 20, 'ml'),
('strawberry-mojito', 'monin-mojito-wild-mint-1-lt', 20, 'ml'),
('yellow-submarine', 'sun-fresh-orange-juice-2lt', 50, 'ml'),
('yellow-submarine', 'dripp-osmantus-760-ml', 10, 'ml'),
('yellow-submarine', 'wilmond-peach-halves', 30, 'gr'),
('yellow-submarine', 'hydro-coco-250-ml', 0.5, 'pcs'),
('cappucino-hot', 'hara-blend-1kg', 20, 'gr'),
('cappucino-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 150, 'ml'),
('latte-hot', 'hara-blend-1kg', 20, 'gr'),
('latte-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 200, 'ml'),
('latte-ice', 'hara-blend-1kg', 20, 'gr'),
('latte-ice', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 200, 'ml'),
('magic-hot', 'hara-blend-1kg', 20, 'gr'),
('magic-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 180, 'ml'),
('creme-brulee', 'hara-blend-1kg', 20, 'gr'),
('creme-brulee', 'brown-sugar-stick-250-pcs-pack', 6, 'pcs'),
('creme-brulee', 'millac-gold-cream-whipping-1-lt', 30, 'ml'),
('creme-brulee', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 100, 'ml'),
('black-coffee-hot', 'hara-blend-1kg', 20, 'gr'),
('black-coffee-ice', 'hara-blend-1kg', 20, 'gr'),
('affogato', 'hara-blend-1kg', 20, 'gr'),
('affogato', 'ice-cream-diamond-vanilla-8-lt', 150, 'gr'),
('hara-iced-coffee', 'kopi-gula-aren', 170, 'ml'),
('pistachio-cloud-latte', 'kopi-gula-aren', 150, 'ml'),
('pistachio-cloud-latte', 'base-cream', 40, 'ml'),
('pistachio-cloud-latte', 'stir-up-pistachio-800-ml', 10, 'ml'),
('sea-salt-cloud-latte', 'kopi-gula-aren', 20, 'ml'),
('sea-salt-cloud-latte', 'base-cream', 40, 'ml'),
('salted-caramel-cloud-latte', 'kopi-gula-aren', 20, 'ml'),
('salted-caramel-cloud-latte', 'base-cream', 200, 'ml'),
('salted-caramel-cloud-latte', 'giffard-caramel-syrup-1lt', 10, 'ml'),
('spanish-latte-hot', 'hara-blend-1kg', 20, 'gr'),
('spanish-latte-hot', 'skm-carnation-370-gr', 20, 'can'),
('spanish-latte-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 180, 'ml'),
('spanish-latte-ice', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 40, 'ml'),
('spanish-latte-ice', 'skm-carnation-370-gr', 30, 'can'),
('hazelnut-caramel-latte', 'hara-blend-1kg', 20, 'gr'),
('hazelnut-caramel-latte', 'giffard-hazelnut-syrup-1lt', 10, 'ml'),
('hazelnut-caramel-latte', 'giffard-caramel-syrup-1lt', 5, 'ml'),
('hazelnut-caramel-latte', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 50, 'ml'),
('hazelnut-caramel-latte', 'oatside-oatmilk-barista-blend-1l', 70, 'ml'),
('hazelnut-caramel-latte', 'millac-gold-cream-whipping-1-lt', 30, 'ml'),
('yuzu-black', 'hara-blend-1kg', 30, 'gr'),
('yuzu-black', 'yuzu-marmalade-kaeru-yuzu-500-gr', 20, 'gr'),
('yuzu-black', 'dried-lemon-slice', 1, 'slice'),
('peach-black', 'hara-blend-1kg', 20, 'gr'),
('peach-black', 'wilmond-peach-halves', 60, 'gr'),
('peach-black', 'giffard-syrup-peach-1lt', 20, 'ml'),
('punchpresso', 'hara-blend-1kg', 20, 'gr'),
('punchpresso', 'giffard-syrup-peach-1lt', 10, 'ml'),
('punchpresso', 'monin-lychee-1lt', 10, 'ml'),
('punchpresso', 'dried-lemon-slice', 1, 'slice'),
('cold-brew', 'cold-brew-base', 150, 'ml'),
('mont-blanc', 'cold-brew-base', 120, 'ml'),
('mont-blanc', 'base-cream', 40, 'ml'),
('dark-berry', 'cold-brew-base', 120, 'ml'),
('dark-berry', 'happy-day-jus-pineapple-1ltr', 20, 'ml'),
('dark-berry', 'monin-geradine-700-ml', 20, 'ml'),
('dark-berry', 'strawberry-garnish', 5, 'gr'),
('matcha-latte-hot', 'matcha-flavor-powder-500grm', 4, 'gr'),
('matcha-latte-hot', 'base-cream', 30, 'ml'),
('matcha-latte-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 200, 'ml'),
('matcha-latte-iced', 'matcha-flavor-powder-500grm', 5, 'gr'),
('matcha-latte-iced', 'base-cream', 30, 'ml'),
('matcha-latte-iced', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 120, 'ml'),
('chocolatte-hot', 'oh-java-cocoa-powder-dark-1kg', 12, 'gr'),
('chocolatte-hot', 'base-cream', 30, 'ml'),
('chocolatte-hot', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 200, 'ml'),
('chocolatte-iced', 'oh-java-cocoa-powder-dark-1kg', 15, 'gr'),
('chocolatte-iced', 'base-cream', 30, 'ml'),
('chocolatte-iced', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 120, 'ml');

insert into public.prep_recipes (item_id, yield_qty, yield_unit) values
('base-cream', 40, 'ml'),
('kopi-gula-aren', 170, 'ml'),
('tea-based', 300, 'ml'),
('cold-brew-base', 150, 'ml');

insert into public.prep_components (prep_item_id, item_id, qty, unit) values
('base-cream', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 10, 'ml'),
('base-cream', 'millac-gold-cream-whipping-1-lt', 30, 'ml'),
('base-cream', 'skm-carnation-370-gr', 5, 'gr'),
('kopi-gula-aren', 'hara-blend-1kg', 20, 'gr'),
('kopi-gula-aren', 'palm-sugar-1-kg-pack', 15, 'gr'),
('kopi-gula-aren', 'millac-gold-cream-whipping-1-lt', 30, 'ml'),
('kopi-gula-aren', 'greenfields-fresh-milk-1-lt-12-pack-ctn', 120, 'ml'),
('tea-based', 'goalpara-black-tea-250-gr-pack', 8, 'gr'),
('cold-brew-base', 'hara-blend-1kg', 20, 'gr');
